### ISSUE TITLE
Java issue

### ISSUE THREAD

**Issue by MingleiYang** [BDM-Lab/3DMax#1]
Hi, 

Thank you so much for developing this application, which helps us to understand the chromatin organisation better,

recently i tried to test this application and i came across this issue, which i think it related to my own Java setting. But i cannot figure out, could you please provide me some suggestions?

```
❯ java -jar 3DMax.jar parameters.txt
3DMax for Genome Structure.
INSTRUCTION:
 (1) Input the file containing the parameters.

Number of points: 57
Number of constraints: 1549
Max distance is: 40.475829797164664
Number of processors:1
Iteration 1, objective function:-252.13383, length of gradient 0.7558897
Iteration 2, objective function:-244.43569, length of gradient 0.7905352
Iteration 3, objective function:-238.78197, length of gradient 0.7799960
Iteration 4, objective function:-234.96316, length of gradient 0.7274894
Iteration 5, objective function:-232.30583, length of gradient 0.6571125
Iteration 6, objective function:-230.27198, length of gradient 0.5987227
Iteration 7, objective function:-228.54458, length of gradient 0.5605558
Iteration 8, objective function:-226.98277, length of gradient 0.5377645
Iteration 9, objective function:-225.52422, length of gradient 0.5243070
Iteration 10, objective function:-224.14033, length of gradient 0.5161492
Iteration 11, objective function:-222.81655, length of gradient 0.5108110
Iteration 12, objective function:-221.53200, length of gradient 0.5090633
Iteration 13, objective function:-220.27202, length of gradient 0.5105723
Iteration 14, objective function:-219.03202, length of gradient 0.5137362
Iteration 15, objective function:-217.81285, length of gradient 0.5177603
Iteration 16, objective function:-216.61836, length of gradient 0.5219569
Iteration 17, objective function:-215.44930, length of gradient 0.5260740
Iteration 18, objective function:-214.29994, length of gradient 0.5307352
Iteration 19, objective function:-213.15945, length of gradient 0.5367613
Iteration 20, objective function:-212.01458, length of gradient 0.5458892
Iteration 21, objective function:-210.88005, length of gradient 0.5551087
Iteration 22, objective function:-209.78375, length of gradient 0.5592186
Iteration 23, objective function:-208.74280, length of gradient 0.5585946
Iteration 24, objective function:-207.76681, length of gradient 0.5541137
Iteration 25, objective function:-206.86012, length of gradient 0.5464080
Iteration 26, objective function:-206.02301, length of gradient 0.5361533
Iteration 27, objective function:-205.25364, length of gradient 0.5239310
Iteration 28, objective function:-204.54970, length of gradient 0.5100208
Iteration 29, objective function:-203.90865, length of gradient 0.4945872
Iteration 30, objective function:-203.32716, length of gradient 0.4779312
Iteration 31, objective function:-202.80098, length of gradient 0.4604724
Iteration 32, objective function:-202.32555, length of gradient 0.4425773
Iteration 33, objective function:-201.89689, length of gradient 0.4244110
Iteration 34, objective function:-201.51120, length of gradient 0.4061722
Iteration 35, objective function:-201.16435, length of gradient 0.3881629
Iteration 36, objective function:-200.85197, length of gradient 0.3706628
Iteration 37, objective function:-200.56971, length of gradient 0.3538922
Iteration 38, objective function:-200.31352, length of gradient 0.3379896
Iteration 39, objective function:-200.08000, length of gradient 0.3229730
Iteration 40, objective function:-199.86658, length of gradient 0.3087510
Iteration 41, objective function:-199.67134, length of gradient 0.2952036
Iteration 42, objective function:-199.49275, length of gradient 0.2822549
Iteration 43, objective function:-199.32939, length of gradient 0.2698886
Iteration 44, objective function:-199.17989, length of gradient 0.2581308
Iteration 45, objective function:-199.04285, length of gradient 0.2470292
Iteration 46, objective function:-198.91684, length of gradient 0.2366319
Iteration 47, objective function:-198.80050, length of gradient 0.2269710
Iteration 48, objective function:-198.69251, length of gradient 0.2180543
Iteration 49, objective function:-198.59173, length of gradient 0.2098644
Iteration 50, objective function:-198.49718, length of gradient 0.2023506
Iteration 51, objective function:-198.40819, length of gradient 0.1954200
Iteration 52, objective function:-198.32434, length of gradient 0.1889493
Iteration 53, objective function:-198.24541, length of gradient 0.1828321
Iteration 54, objective function:-198.17121, length of gradient 0.1770371
Iteration 55, objective function:-198.10141, length of gradient 0.1716351
Iteration 56, objective function:-198.03551, length of gradient 0.1667716
Iteration 57, objective function:-197.97290, length of gradient 0.1625671
Iteration 58, objective function:-197.91308, length of gradient 0.1589418
Iteration 59, objective function:-197.85598, length of gradient 0.1555140
Iteration 60, objective function:-197.80185, length of gradient 0.1518030
Iteration 61, objective function:-197.75108, length of gradient 0.1475581
Iteration 62, objective function:-197.70395, length of gradient 0.1428175
Iteration 63, objective function:-197.66053, length of gradient 0.1377581
Iteration 64, objective function:-197.62074, length of gradient 0.1325661
Iteration 65, objective function:-197.58442, length of gradient 0.1273884
Iteration 66, objective function:-197.55131, length of gradient 0.1223267
Iteration 67, objective function:-197.52115, length of gradient 0.1174459
Iteration 68, objective function:-197.49367, length of gradient 0.1127841
Iteration 69, objective function:-197.46859, length of gradient 0.1083603
Iteration 70, objective function:-197.44568, length of gradient 0.1041799
Iteration 71, objective function:-197.42469, length of gradient 0.1002397
Iteration 72, objective function:-197.40542, length of gradient 0.0965303
Iteration 73, objective function:-197.38769, length of gradient 0.0930394
Iteration 74, objective function:-197.37133, length of gradient 0.0897528
Iteration 75, objective function:-197.35620, length of gradient 0.0866561
Iteration 76, objective function:-197.34218, length of gradient 0.0837357
Iteration 77, objective function:-197.32916, length of gradient 0.0809790
Iteration 78, objective function:-197.31703, length of gradient 0.0783747
Iteration 79, objective function:-197.30571, length of gradient 0.0759133
Iteration 80, objective function:-197.29513, length of gradient 0.0735863
Iteration 81, objective function:-197.28521, length of gradient 0.0713869
Iteration 82, objective function:-197.27588, length of gradient 0.0693089
Iteration 83, objective function:-197.26709, length of gradient 0.0673473
Iteration 84, objective function:-197.25878, length of gradient 0.0654973
Iteration 85, objective function:-197.25090, length of gradient 0.0637548
Iteration 86, objective function:-197.24340, length of gradient 0.0621159
Iteration 87, objective function:-197.23625, length of gradient 0.0605769
Iteration 88, objective function:-197.22940, length of gradient 0.0591342
Iteration 89, objective function:-197.22281, length of gradient 0.0577844
Iteration 90, objective function:-197.21645, length of gradient 0.0565240
Iteration 91, objective function:-197.21029, length of gradient 0.0553500
Iteration 92, objective function:-197.20430, length of gradient 0.0542594
Iteration 93, objective function:-197.19845, length of gradient 0.0532498
Iteration 94, objective function:-197.19270, length of gradient 0.0523191
Iteration 95, objective function:-197.18705, length of gradient 0.0514657
Iteration 96, objective function:-197.18146, length of gradient 0.0506885
Iteration 97, objective function:-197.17591, length of gradient 0.0499864
Iteration 98, objective function:-197.17037, length of gradient 0.0493579
Iteration 99, objective function:-197.16482, length of gradient 0.0488003
Iteration 100, objective function:-197.15925, length of gradient 0.0483091
Iteration 101, objective function:-197.15364, length of gradient 0.0478769
Iteration 102, objective function:-197.14798, length of gradient 0.0474931
Iteration 103, objective function:-197.14226, length of gradient 0.0471442
Iteration 104, objective function:-197.13648, length of gradient 0.0468151
Iteration 105, objective function:-197.13067, length of gradient 0.0464911
Iteration 106, objective function:-197.12482, length of gradient 0.0461600
Iteration 107, objective function:-197.11895, length of gradient 0.0458144
Iteration 108, objective function:-197.11309, length of gradient 0.0454523
Iteration 109, objective function:-197.10724, length of gradient 0.0450766
Iteration 110, objective function:-197.10141, length of gradient 0.0446930
Iteration 111, objective function:-197.09561, length of gradient 0.0443069
Iteration 112, objective function:-197.08984, length of gradient 0.0439204
Iteration 113, objective function:-197.08412, length of gradient 0.0435302
Iteration 114, objective function:-197.07846, length of gradient 0.0431271
Iteration 115, objective function:-197.07287, length of gradient 0.0426974
Iteration 116, objective function:-197.06739, length of gradient 0.0422258
Iteration 117, objective function:-197.06205, length of gradient 0.0417003
Iteration 118, objective function:-197.05688, length of gradient 0.0411148
Iteration 119, objective function:-197.05192, length of gradient 0.0404716
Iteration 120, objective function:-197.04719, length of gradient 0.0397812
Iteration 121, objective function:-197.04271, length of gradient 0.0390594
Iteration 122, objective function:-197.03848, length of gradient 0.0383248
Iteration 123, objective function:-197.03449, length of gradient 0.0375954
Iteration 124, objective function:-197.03073, length of gradient 0.0368866
Iteration 125, objective function:-197.02718, length of gradient 0.0362104
Iteration 126, objective function:-197.02383, length of gradient 0.0355745
Iteration 127, objective function:-197.02066, length of gradient 0.0349836
Iteration 128, objective function:-197.01763, length of gradient 0.0344393
Iteration 129, objective function:-197.01474, length of gradient 0.0339408
Iteration 130, objective function:-197.01196, length of gradient 0.0334857
Iteration 131, objective function:-197.00928, length of gradient 0.0330702
Iteration 132, objective function:-197.00669, length of gradient 0.0326894
Iteration 133, objective function:-197.00417, length of gradient 0.0323372
Iteration 134, objective function:-197.00172, length of gradient 0.0320067
Iteration 135, objective function:-196.99933, length of gradient 0.0316907
Iteration 136, objective function:-196.99701, length of gradient 0.0313815
Iteration 137, objective function:-196.99474, length of gradient 0.0310720
Iteration 138, objective function:-196.99253, length of gradient 0.0307561
Iteration 139, objective function:-196.99039, length of gradient 0.0304291
Iteration 140, objective function:-196.98832, length of gradient 0.0300882
Iteration 141, objective function:-196.98633, length of gradient 0.0297326
Iteration 142, objective function:-196.98441, length of gradient 0.0293632
Iteration 143, objective function:-196.98257, length of gradient 0.0289823
Iteration 144, objective function:-196.98081, length of gradient 0.0285930
Iteration 145, objective function:-196.97913, length of gradient 0.0281987
Iteration 146, objective function:-196.97753, length of gradient 0.0278027
Iteration 147, objective function:-196.97601, length of gradient 0.0274078
Iteration 148, objective function:-196.97455, length of gradient 0.0270162
Iteration 149, objective function:-196.97316, length of gradient 0.0266298
Iteration 150, objective function:-196.97183, length of gradient 0.0262495
Iteration 151, objective function:-196.97057, length of gradient 0.0258760
Iteration 152, objective function:-196.96936, length of gradient 0.0255096
Iteration 153, objective function:-196.96820, length of gradient 0.0251502
Iteration 154, objective function:-196.96709, length of gradient 0.0247976
Iteration 155, objective function:-196.96602, length of gradient 0.0244516
Iteration 156, objective function:-196.96500, length of gradient 0.0241117
Iteration 157, objective function:-196.96401, length of gradient 0.0237775
Iteration 158, objective function:-196.96306, length of gradient 0.0234486
Iteration 159, objective function:-196.96215, length of gradient 0.0231246
Iteration 160, objective function:-196.96127, length of gradient 0.0228053
Iteration 161, objective function:-196.96042, length of gradient 0.0224902
Iteration 162, objective function:-196.95959, length of gradient 0.0221791
Iteration 163, objective function:-196.95880, length of gradient 0.0218718
Iteration 164, objective function:-196.95803, length of gradient 0.0215681
Iteration 165, objective function:-196.95729, length of gradient 0.0212677
Iteration 166, objective function:-196.95657, length of gradient 0.0209706
Iteration 167, objective function:-196.95588, length of gradient 0.0206766
Iteration 168, objective function:-196.95520, length of gradient 0.0203856
Iteration 169, objective function:-196.95455, length of gradient 0.0200975
Iteration 170, objective function:-196.95392, length of gradient 0.0198122
Iteration 171, objective function:-196.95331, length of gradient 0.0195298
Iteration 172, objective function:-196.95272, length of gradient 0.0192500
Iteration 173, objective function:-196.95214, length of gradient 0.0189730
Iteration 174, objective function:-196.95159, length of gradient 0.0186987
Iteration 175, objective function:-196.95105, length of gradient 0.0184270
Iteration 176, objective function:-196.95052, length of gradient 0.0181579
Iteration 177, objective function:-196.95002, length of gradient 0.0178915
Iteration 178, objective function:-196.94952, length of gradient 0.0176276
Iteration 179, objective function:-196.94905, length of gradient 0.0173664
Iteration 180, objective function:-196.94859, length of gradient 0.0171078
Iteration 181, objective function:-196.94814, length of gradient 0.0168518
Iteration 182, objective function:-196.94770, length of gradient 0.0165985
Iteration 183, objective function:-196.94728, length of gradient 0.0163477
Iteration 184, objective function:-196.94687, length of gradient 0.0160996
Iteration 185, objective function:-196.94648, length of gradient 0.0158541
Iteration 186, objective function:-196.94610, length of gradient 0.0156113
Iteration 187, objective function:-196.94572, length of gradient 0.0153710
Iteration 188, objective function:-196.94536, length of gradient 0.0151335
Iteration 189, objective function:-196.94502, length of gradient 0.0148986
Iteration 190, objective function:-196.94468, length of gradient 0.0146664
Iteration 191, objective function:-196.94435, length of gradient 0.0144368
Iteration 192, objective function:-196.94403, length of gradient 0.0142099
Iteration 193, objective function:-196.94373, length of gradient 0.0139857
Iteration 194, objective function:-196.94343, length of gradient 0.0137642
Iteration 195, objective function:-196.94314, length of gradient 0.0135454
Iteration 196, objective function:-196.94286, length of gradient 0.0133292
Iteration 197, objective function:-196.94259, length of gradient 0.0131157
Iteration 198, objective function:-196.94233, length of gradient 0.0129050
Iteration 199, objective function:-196.94208, length of gradient 0.0126969
Iteration 200, objective function:-196.94183, length of gradient 0.0124915
Iteration 201, objective function:-196.94159, length of gradient 0.0122887
Iteration 202, objective function:-196.94136, length of gradient 0.0120886
Iteration 203, objective function:-196.94114, length of gradient 0.0118912
Iteration 204, objective function:-196.94093, length of gradient 0.0116965
Iteration 205, objective function:-196.94072, length of gradient 0.0115044
Iteration 206, objective function:-196.94052, length of gradient 0.0113149
Iteration 207, objective function:-196.94032, length of gradient 0.0111281
Iteration 208, objective function:-196.94013, length of gradient 0.0109438
Iteration 209, objective function:-196.93995, length of gradient 0.0107622
Iteration 210, objective function:-196.93977, length of gradient 0.0105831
Iteration 211, objective function:-196.93960, length of gradient 0.0104067
Iteration 212, objective function:-196.93944, length of gradient 0.0102327
Iteration 213, objective function:-196.93928, length of gradient 0.0100613
Iteration 214, objective function:-196.93912, length of gradient 0.0098925
Iteration 215, objective function:-196.93897, length of gradient 0.0097261
Iteration 216, objective function:-196.93883, length of gradient 0.0095622
Iteration 217, objective function:-196.93869, length of gradient 0.0094008
Iteration 218, objective function:-196.93855, length of gradient 0.0092418
Iteration 219, objective function:-196.93842, length of gradient 0.0090852
Iteration 220, objective function:-196.93830, length of gradient 0.0089310
Iteration 221, objective function:-196.93817, length of gradient 0.0087792
Iteration 222, objective function:-196.93805, length of gradient 0.0086297
Iteration 223, objective function:-196.93794, length of gradient 0.0084826
Iteration 224, objective function:-196.93783, length of gradient 0.0083377
Iteration 225, objective function:-196.93772, length of gradient 0.0081952
Iteration 226, objective function:-196.93762, length of gradient 0.0080549
Iteration 227, objective function:-196.93752, length of gradient 0.0079168
Iteration 228, objective function:-196.93742, length of gradient 0.0077809
Iteration 229, objective function:-196.93733, length of gradient 0.0076472
Iteration 230, objective function:-196.93724, length of gradient 0.0075156
Iteration 231, objective function:-196.93715, length of gradient 0.0073862
Iteration 232, objective function:-196.93707, length of gradient 0.0072589
Iteration 233, objective function:-196.93699, length of gradient 0.0071336
Iteration 234, objective function:-196.93691, length of gradient 0.0070104
Iteration 235, objective function:-196.93683, length of gradient 0.0068892
Iteration 236, objective function:-196.93676, length of gradient 0.0067700
Iteration 237, objective function:-196.93669, length of gradient 0.0066527
Iteration 238, objective function:-196.93662, length of gradient 0.0065374
Iteration 239, objective function:-196.93656, length of gradient 0.0064240
Iteration 240, objective function:-196.93649, length of gradient 0.0063125
Iteration 241, objective function:-196.93643, length of gradient 0.0062029
Iteration 242, objective function:-196.93637, length of gradient 0.0060951
Iteration 243, objective function:-196.93631, length of gradient 0.0059891
Iteration 244, objective function:-196.93626, length of gradient 0.0058848
Iteration 245, objective function:-196.93620, length of gradient 0.0057824
Iteration 246, objective function:-196.93615, length of gradient 0.0056816
Iteration 247, objective function:-196.93610, length of gradient 0.0055826
Iteration 248, objective function:-196.93605, length of gradient 0.0054852
Iteration 249, objective function:-196.93601, length of gradient 0.0053895
Iteration 250, objective function:-196.93596, length of gradient 0.0052954
Iteration 251, objective function:-196.93592, length of gradient 0.0052030
Iteration 252, objective function:-196.93588, length of gradient 0.0051121
Iteration 253, objective function:-196.93584, length of gradient 0.0050227
Iteration 254, objective function:-196.93580, length of gradient 0.0049349
Iteration 255, objective function:-196.93576, length of gradient 0.0048486
Iteration 256, objective function:-196.93572, length of gradient 0.0047638
Iteration 257, objective function:-196.93569, length of gradient 0.0046805
Iteration 258, objective function:-196.93565, length of gradient 0.0045985
Iteration 259, objective function:-196.93562, length of gradient 0.0045180
Iteration 260, objective function:-196.93559, length of gradient 0.0044389
Iteration 261, objective function:-196.93556, length of gradient 0.0043612
Iteration 262, objective function:-196.93553, length of gradient 0.0042848
Iteration 263, objective function:-196.93550, length of gradient 0.0042097
Iteration 264, objective function:-196.93547, length of gradient 0.0041359
Iteration 265, objective function:-196.93544, length of gradient 0.0040634
Iteration 266, objective function:-196.93542, length of gradient 0.0039922
Iteration 267, objective function:-196.93539, length of gradient 0.0039222
Iteration 268, objective function:-196.93537, length of gradient 0.0038534
Iteration 269, objective function:-196.93534, length of gradient 0.0037858
Iteration 270, objective function:-196.93532, length of gradient 0.0037194
Iteration 271, objective function:-196.93530, length of gradient 0.0036542
Iteration 272, objective function:-196.93528, length of gradient 0.0035900
Iteration 273, objective function:-196.93526, length of gradient 0.0035271
Iteration 274, objective function:-196.93524, length of gradient 0.0034652
Iteration 275, objective function:-196.93522, length of gradient 0.0034044
Iteration 276, objective function:-196.93520, length of gradient 0.0033446
Iteration 277, objective function:-196.93518, length of gradient 0.0032860
Iteration 278, objective function:-196.93517, length of gradient 0.0032283
Iteration 279, objective function:-196.93515, length of gradient 0.0031716
Iteration 280, objective function:-196.93514, length of gradient 0.0031160
Iteration 281, objective function:-196.93512, length of gradient 0.0030613
Iteration 282, objective function:-196.93511, length of gradient 0.0030076
Iteration 283, objective function:-196.93509, length of gradient 0.0029548
Iteration 284, objective function:-196.93508, length of gradient 0.0029029
Iteration 285, objective function:-196.93506, length of gradient 0.0028520
Iteration 286, objective function:-196.93505, length of gradient 0.0028020
Iteration 287, objective function:-196.93504, length of gradient 0.0027528
Iteration 288, objective function:-196.93503, length of gradient 0.0027045
Iteration 289, objective function:-196.93502, length of gradient 0.0026571
Iteration 290, objective function:-196.93500, length of gradient 0.0026104
Iteration 291, objective function:-196.93499, length of gradient 0.0025646
Iteration 292, objective function:-196.93498, length of gradient 0.0025197
Iteration 293, objective function:-196.93497, length of gradient 0.0024755
Iteration 294, objective function:-196.93496, length of gradient 0.0024320
Iteration 295, objective function:-196.93495, length of gradient 0.0023894
Iteration 296, objective function:-196.93494, length of gradient 0.0023475
Iteration 297, objective function:-196.93494, length of gradient 0.0023063
Iteration 298, objective function:-196.93493, length of gradient 0.0022659
Iteration 299, objective function:-196.93492, length of gradient 0.0022262
Iteration 300, objective function:-196.93491, length of gradient 0.0021871
Iteration 301, objective function:-196.93490, length of gradient 0.0021488
Iteration 302, objective function:-196.93490, length of gradient 0.0021111
Iteration 303, objective function:-196.93489, length of gradient 0.0020741
Iteration 304, objective function:-196.93488, length of gradient 0.0020378
Iteration 305, objective function:-196.93488, length of gradient 0.0020021
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/math3/stat/correlation/SpearmansCorrelation
	at evaluation.Evaluate.calSpearmanCorrelation(Evaluate.java:257)
	at evaluation.CalRMSD.correlationIFvsDist(CalRMSD.java:141)
	at algorithm.StructureGenerator3DMax.run(StructureGenerator3DMax.java:480)
	at algorithm.StructureGenerator3DMax.generateStructure(StructureGenerator3DMax.java:411)
	at algorithm.StructureGenerator3DMax.main(StructureGenerator3DMax.java:769)
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.math3.stat.correlation.SpearmansCorrelation
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 10 more
```

**Comment by yoeHuuui** [comment]
I met the same problem some days ago, and then I install the openjdk-8-jdk. Now, I solved this problem. Maybe caused the version! More information you can clicked this link: https://stackoverflow.com/questions/59986900/exception-in-thread-main-java-lang-reflect-invocationtargetexception-while-ins
